# Test against this version of Node.js
environment:
  matrix:
  # node.js
  - nodejs_version: "6"

# Install scripts. (Run afer repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env_nodejs_version
  # Install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Run test
  - npm test

# Don't actually build.
build: off
